import numpy as np

def parameter(temp, steps=100000, trail=100, lattice_size=1000):
    """
    Alloy parameter for hypo system in selfdiffusion
    """
    alloy_1A_para = {
        "1A": {
            "elements": 1,
            "concentrsation": [1],
            "migration_energy_mu": np.array([1]),
            "migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        }
    }
    alloy_1Ab_para = {
        "1Abwb0": {
            "elements": 2,
            "concentration": [0.99, 0.01],
            "migration_energy_mu": np.array([0.8, 1.2]),
            "migration_energy_sigma": np.array([0, 0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "1Abwb1": {
            "elements": 2,
            "concentration": [0.99, 0.01],
            "migration_energy_mu": np.array([1.2, 0.8]),
            "migration_energy_sigma": np.array([0, 0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "1Abnb0": {
            "elements": 2,
            "concentration": [0.99, 0.01],
            "migration_energy_mu": np.array([0.9, 1.1]),
            "migration_energy_sigma": np.array([0, 0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "1Abnb1": {
            "elements": 2,
            "concentration": [0.99, 0.01],
            "migration_energy_mu": np.array([1.1, 0.9]),
            "migration_energy_sigma": np.array([0, 0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
    }
    alloy_2A_para_WB = {
        "2A-wb0": {
            "elements": 2,
            "concentration": [0.5, 0.5],
            "migration_energy_mu": np.array([0.8, 1.2]),
            "migration_energy_sigma": np.array([0, 0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "2A-wb0.1": {
            "elements": 2,
            "concentration": [0.5, 0.5],
            "migration_energy_mu": np.array([0.8, 1.2]),
            "migration_energy_sigma": np.array([0.1, 0.1]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "2A-wb0.2": {
            "elements": 2,
            "concentration": [0.5, 0.5],
            "migration_energy_mu": np.array([0.8, 1.2]),
            "migration_energy_sigma": np.array([0.2, 0.2]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "2A-wb0.3": {
            "elements": 2,
            "concentration": [0.5, 0.5],
            "migration_energy_mu": np.array([0.8, 1.2]),
            "migration_energy_sigma": np.array([0.3, 0.3]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
    }
    alloy_2A_para_NB = {
        "2A-nb0": {
            "elements": 2,
            "concentration": [0.5, 0.5],
            "migration_energy_mu": np.array([0.9, 1.1]),
            "migration_energy_sigma": np.array([0, 0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "2A-nb0.1": {
            "elements": 2,
            "concentration": [0.5, 0.5],
            "migration_energy_mu": np.array([0.9, 1.1]),
            "migration_energy_sigma": np.array([0.1, 0.1]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "2A-nb0.2": {
            "elements": 2,
            "concentration": [0.5, 0.5],
            "migration_energy_mu": np.array([0.9, 1.1]),
            "migration_energy_sigma": np.array([0.2, 0.2]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "2A-nb0.3": {
            "elements": 2,
            "concentration": [0.5, 0.5],
            "migration_energy_mu": np.array([0.9, 1.1]),
            "migration_energy_sigma": np.array([0.3, 0.3]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
    }
    alloy_3A_para_WB = {
        "3A-wb0": {
            "elements": 3,
            "concentration": [1 / 3, 1 / 3, 1 / 3],
            "migration_energy_mu": np.array([0.8, 1.0, 1.2]),
            "migration_energy_sigma": np.array([0, 0, 0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "3A-wb0.1": {
            "elements": 3,
            "concentration": [1 / 3, 1 / 3, 1 / 3],
            "migration_energy_mu": np.array([0.8, 1.0, 1.2]),
            "migration_energy_sigma": np.array([0.1, 0.1, 0.1]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "3A-wb0.2": {
            "elements": 3,
            "concentration": [1 / 3, 1 / 3, 1 / 3],
            "migration_energy_mu": np.array([0.8, 1.0, 1.2]),
            "migration_energy_sigma": np.array([0.2, 0.2, 0.2]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "3A-wb0.3": {
            "elements": 3,
            "concentration": [1 / 3, 1 / 3, 1 / 3],
            "migration_energy_mu": np.array([0.8, 1.0, 1.2]),
            "pm_migration_energy_sigma": np.array([0.3, 0.3, 0.3]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
    }
    alloy_3A_para_NB = {
        "3A-nb0": {
            "elements": 3,
            "concentration": [1 / 3, 1 / 3, 1 / 3],
            "migration_energy_mu": np.array([0.9, 1.0, 1.1]),
            "migration_energy_sigma": np.array([0, 0, 0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "3A-nb0.1": {
            "elements": 3,
            "concentration": [1 / 3, 1 / 3, 1 / 3],
            "migration_energy_mu": np.array([0.9, 1.0, 1.1]),
            "migration_energy_sigma": np.array([0.1, 0.1, 0.1]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "3A-nb0.2": {
            "elements": 3,
            "concentration": [1 / 3, 1 / 3, 1 / 3],
            "migration_energy_mu": np.array([0.9, 1.0, 1.1]),
            "migration_energy_sigma": np.array([0.2, 0.2, 0.2]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "3A-nb0.3": {
            "elements": 3,
            "concentration": [1 / 3, 1 / 3, 1 / 3],
            "migration_energy_mu": np.array([0.9, 1.0, 1.1]),
            "migration_energy_sigma": np.array([0.3, 0.3, 0.3]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
    }
    alloy_4A_para_WB = {
        "4A-nb0": {
            "elements": 4,
            "concentration": [0.25, 0.25, 0.25, 0.25],
            "migration_energy_mu": np.array([0.85, 0.95, 1.05, 1.15]),
            "migration_energy_sigma": np.array([0, 0, 0, 0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "4A-nb0.1": {
            "elements": 4,
            "concentration": [0.25, 0.25, 0.25, 0.25],
            "migration_energy_mu": np.array([0.85, 0.95, 1.05, 1.15]),
            "migration_energy_sigma": np.array([0.1, 0.1, 0.1, 0.1]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "4A-nb0.2": {
            "elements": 4,
            "concentration": [0.25, 0.25, 0.25, 0.25],
            "migration_energy_mu": np.array([0.85, 0.95, 1.05, 1.15]),
            "migration_energy_sigma": np.array([0.2, 0.2, 0.2, 0.2]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "4A-nb0.3": {
            "elements": 4,
            "concentration": [0.25, 0.25, 0.25, 0.25],
            "migration_energy_mu": np.array([0.85, 0.95, 1.05, 1.15]),
            "migration_energy_sigma": np.array([0.3, 0.3, 0.3, 0.3]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
    }
    alloy_4A_para_NB = {
        "4A-wb0": {
            "elements": 4,
            "concentration": [0.25, 0.25, 0.25, 0.25],
            "migration_energy_mu": np.array([0.7, 0.9, 1.1, 1.3]),
            "migration_energy_sigma": np.array([0, 0, 0, 0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "4A-wb0.1": {
            "elements": 4,
            "concentration": [0.25, 0.25, 0.25, 0.25],
            "migration_energy_mu": np.array([0.7, 0.9, 1.1, 1.3]),
            "migration_energy_sigma": np.array([0.1, 0.1, 0.1, 0.1]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "4A-wb0.2": {
            "elements": 4,
            "concentration": [0.25, 0.25, 0.25, 0.25],
            "migration_energy_mu": np.array([0.7, 0.9, 1.1, 1.3]),
            "migration_energy_sigma": np.array([0.2, 0.2, 0.2, 0.2]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "4A-wb0.3": {
            "elements": 4,
            "concentration": [0.25, 0.25, 0.25, 0.25],
            "migration_energy_mu": np.array([0.7, 0.9, 1.1, 1.3]),
            "migration_energy_sigma": np.array([0.3, 0.3, 0.3, 0.3]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
    }
    alloy_5A_para_WB = {
        "5A-wb0": {
            "elements": 5,
            "concentration": [0.2, 0.2, 0.2, 0.2, 0.2],
            "migration_energy_mu": np.array([0.6, 0.8, 1.0, 1.2, 1.4]),
            "migration_energy_sigma": np.array([0, 0, 0, 0, 0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "5A-wb0.1": {
            "elements": 5,
            "concentration": [0.2, 0.2, 0.2, 0.2, 0.2],
            "migration_energy_mu": np.array([0.6, 0.8, 1.0, 1.2, 1.4]),
            "migration_energy_sigma": np.array([0.1, 0.1, 0.1, 0.1, 0.1]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "5A-wb0.2": {
            "elements": 5,
            "concentration": [0.2, 0.2, 0.2, 0.2, 0.2],
            "migration_energy_mu": np.array([0.6, 0.8, 1.0, 1.2, 1.4]),
            "migration_energy_sigma": np.array([0.2, 0.2, 0.2, 0.2, 0.2]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "5A-wb0.3": {
            "elements": 5,
            "concentration": [0.2, 0.2, 0.2, 0.2, 0.2],
            "migration_energy_mu": np.array([0.6, 0.8, 1.0, 1.2, 1.4]),
            "migration_energy_sigma": np.array([0.3, 0.3, 0.3, 0.3, 0.3]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
    }
    alloy_5A_para_NB = {
        "5A-nb0": {
            "elements": 5,
            "concentration": [0.2, 0.2, 0.2, 0.2, 0.2],
            "migration_energy_mu": np.array([0.8, 0.9, 1.0, 1.1, 1.2]),
            "migration_energy_sigma": np.array([0, 0, 0, 0, 0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "5A-nb0.1": {
            "elements": 5,
            "concentration": [0.2, 0.2, 0.2, 0.2, 0.2],
            "migration_energy_mu": np.array([0.8, 0.9, 1.0, 1.1, 1.2]),
            "migration_energy_sigma": np.array([0.1, 0.1, 0.1, 0.1, 0.1]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "5A-nb0.2": {
            "elements": 5,
            "concentration": [0.2, 0.2, 0.2, 0.2, 0.2],
            "migration_energy_mu": np.array([0.8, 0.9, 1.0, 1.1, 1.2]),
            "migration_energy_sigma": np.array([0.2, 0.2, 0.2, 0.2, 0.2]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "5A-nb0.3": {
            "elements": 5,
            "concentration": [0.2, 0.2, 0.2, 0.2, 0.2],
            "migration_energy_mu": np.array([0.8, 0.9, 1.0, 1.1, 1.2]),
            "migration_energy_sigma": np.array([0.3, 0.3, 0.3, 0.3, 0.3]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
    }
    return (
        alloy_1A_para,
        alloy_1Ab_para,
        alloy_2A_para_WB,
        alloy_2A_para_NB,
        alloy_3A_para_WB,
        alloy_3A_para_NB,
        alloy_4A_para_WB,
        alloy_4A_para_NB,
        alloy_5A_para_WB,
        alloy_5A_para_NB,
    )

def real_fcc_parameter(temp, steps=100000, trail=100, lattice_size=1000):
    real_system = {
        "Cu": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([0.71]),
            "pm_migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "Co": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([1.05]),
            "pm_migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "Mn": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([0.46]),
            "pm_migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "Ni": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([1.471]),
            "migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "Al": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([0.57]),
            "migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "NiCod": {
            "elements": 2,
            "concentration": [0.99, 0.01],
            "migration_energy_mu": np.array([1.471, 1.651]),
            "migration_energy_sigma": np.array([0,0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "NiCrd": {
            "elements": 2,
            "concentration": [0.99, 0.01],
            "migration_energy_mu": np.array([1.471, 1.625]),
            "migration_energy_sigma": np.array([0,0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "NiFed": {
            "elements": 2,
            "concentration": [0.99, 0.01],
            "migration_energy_mu": np.array([1.471, 1.073]),
            "migration_energy_sigma": np.array([0,0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "NiMnd": {
            "elements": 2,
            "concentration": [0.99, 0.01],
            "migration_energy_mu": np.array([1.471, 0.85]),
            "migration_energy_sigma": np.array([0,0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "NiCo": {
            "elements": 2,
            "concentration": [0.5, 0.5],
            "migration_energy_mu": np.array([0.81, 0.856]),
            "migration_energy_sigma": np.array([0.1,0.1]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "NiFe": {
            "elements": 2,
            "concentration": [0.5, 0.5],
            "migration_energy_mu": np.array([1.41,1.06]),
            "migration_energy_sigma": np.array([0.11,0.067]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "NiCoCr": {
            "elements": 3,
            "concentration": [0.5, 0.25, 0.25],
            "migration_energy_mu": np.array([0.58,0.62,0.61]),
            "migration_energy_sigma": np.array([0.12,0.17,0.15]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "CoCrFeMnNi20": {
            "elements": 5,
            "concentration": [0.2,0.2,0.2,0.2,0.2],
            "migration_energy_mu": np.array([1.045,0.869,0.68,0.493,0.985]),
            "migration_energy_sigma": np.array([0.224,0.295,0.164,0.168,0.208]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "CoCrFeMnNi60": {
            "elements": 5,
            "concentration": [0.1,0.1,0.1,0.1,0.6],
            "migration_energy_mu": np.array([1.31,1.261,0.862,0.707,1.216]),
            "migration_energy_sigma": np.array([0.172,0.267,0.163,0.135,0.166]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "CoCrFeMnNi80": {
            "elements": 5,
            "concentration": [0.05,0.05,0.05,0.05,0.8],
            "migration_energy_mu": np.array([1.445,1.465,0.975,0.775,1.339]),
            "migration_energy_sigma": np.array([0.122,0.192,0.14,0.111,0.115]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "CoCrFeMnNi92": {
            "elements": 5,
            "concentration": [0.02,0.02,0.02,0.02,0.92],
            "migration_energy_mu": np.array([1.57,1.563,1.048,0.82,1.421]),
            "migration_energy_sigma": np.array([0.079,0.144,0.083,0.086,0.085]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
    }

    return real_system

def real_bcc_parameter(temp,steps=100000, trail=100, lattice_size=1000):
    real_system = {
        # Reference: Acta Materialia 109 (2016): 128-14
        # DFT
        "Mo": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([1.23]),
            "pm_migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "Cr": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([0.9]),
            "pm_migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "Fe": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([0.73]),
            "pm_migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "V_1": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([0.46]),
            "pm_migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "Ta_1": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([0.75]),
            "pm_migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
       
        "Nb": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([0.43]),
            "pm_migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "W": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([1.82]),
            "pm_migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "NbMoTa": {
            "elements": 3,
            "concentration": [1/3,1/3,1/3],
            "migration_energy_mu": np.array([1.44,1.48,1.71]),
            "migration_energy_sigma": np.array([0.18,0.14,0.23]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        # Reference:Dou, Journal of Nuclear Materials 573 (2023): 154096.
        # DFT calculation
        "V_2": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([0.62]),
            "pm_migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },

        "Ta_2": {
            "elements": 1,
            "concentration": [1],
            "migration_energy_mu": np.array([1.48]),
            "pm_migration_energy_sigma": np.array([0]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },

        "TiVTa": {
            "elements": 3,
            "concentration": [1/3,1/3,1/3],
            "migration_energy_mu": np.array([0.41,0.54,0.51]),
            "migration_energy_sigma": np.array([0.23,0.27,0.26]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "TiVTa50": {
            "elements": 3,
            "concentration": [0.25,0.25,0.5],
            "migration_energy_mu": np.array([0.38,0.57,0.52]),
            "migration_energy_sigma": np.array([0.18,0.28,0.26]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        "TiVTaNb": {
            "elements": 4,
            "concentration": [0.25,0.25,0.25,0.25],
            "migration_energy_mu": np.array([0.47,0.7,0.6,0.57]),
            "migration_energy_sigma": np.array([0.17,0.37,0.34,0.28]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
        # Reference: Journal of Materials Science & Technology 44 (2020): 133-139.
        # DFT
        "VTaCrW": {
            "elements": 4,
            "concentration": [0.25,0.25,0.25,0.25],
            "migration_energy_mu": np.array([1,0.71,1.11,1.15]),
            "migration_energy_sigma": np.array([0.1,0.1,0.1,0.1]),
            "tempartemperature":temp,
            "steps": steps,
            "trail": trail,
            "lattice": lattice_size,
        },
    }


def lattice_const():
    # hyposystem
    {
        "sc":0.30,
        "bcc":0.32,
        "fcc":0.35,

    }
    #realsystem
    { "W" : 0.316,
        "Cr": 0.288,
        "Fe": 0.287,
        "Mo": 0.315,
        "Nb": 0.330,
        "Al": 0.405,
        "Co": 0.355,
        "Cu": 0.361,
        "Mn": 0.3564,
        "Ni": 0.352,
        "V_1": 0.302,
        "V_2": 0.302,
        "Ta_1":  0.331,
        "Ta_2": 0.331,
        "NiCod": 0.352,
        "NiCrd": 0.352,
        "NiFed": 0.352,
        "NiMnd": 0.352,
        "NiCo0.5":0.3532,
        "NiFe0.5":0.35,
        "Ni(CoCr)0.5":0.354,
        "NbMoTa":0.32,
        "TiVTa":0.32,
        "TiVTa0.5":0.32,
        "TiVTaNb":0.31,
        "VTaCrW":0.3102,
        # Materials Science and Engineering: A 696 (2017): 228-235.
        "CoCrFeMnNi20": 0.3601,
        "CoCrFeMnNi60": 0.3579,
        "CoCrFeMnNi80": 0.355,
        "CoCrFeMnNi92": 0.3539,}
    return